webAuxiliar/Controllers/AuxObraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using model.DEL;
using model.BEL;
using Website.Utils;

//AuxiliarWeb
namespace webAuxiliar.Controllers
{
    public class AuxObraController : Controller
    {
        //inicializar
        private AuxObraBEL objAuxObraBEL;

        public AuxObraController()
        {
            objAuxObraBEL = new AuxObraBEL();
        }

        // GET: AuxObra
        public ActionResult Inicio()
        {
            List<AuxiliarObra> listaAuxObra = objAuxObraBEL.findAll();
            return View(listaAuxObra);
            //return null;
        }

        [HttpGet]
        public ActionResult findAuxObraNro(string txtAuxNro)
        {

            if (txtAuxNro == "")
            {
                txtAuxNro = "-1";
            }

            AuxiliarObra objAuxObraNro = new AuxiliarObra();
            objAuxObraNro.NumeroAux = txtAuxNro;
            List<AuxiliarObra> AuxiliarObra = objAuxObraBEL.findAuxObraNro(objAuxObraNro);
            return View(AuxiliarObra);
        }

        [HttpGet]
        public ActionResult findAuxObraDate(string txtfechaDesde, string txtFechaHasta)
        {
            //AuxiliarObra objAuxObraDate = new AuxiliarObra();
            List<AuxiliarObra> listaAuxObraDate = objAuxObraBEL.findAuxObraDate(txtfechaDesde, txtFechaHasta);

            Utils.GlobalVarAux.fechaDesde = txtfechaDesde;
            Utils.GlobalVarAux.fechaHasta = txtFechaHasta;

            return View(listaAuxObraDate);

            //return null;
        }


        [HttpGet]
        public JsonResult getAuxObra(string sidx, string sord, int page, int rows, bool _search,
                                     string searchField, string searchOper, string searchString,
                                     string beginDate, string endDate)
        {

            List<AuxiliarObra> listaAuxObra;

            if (beginDate == "" || endDate == "")
            {

                listaAuxObra = objAuxObraBEL.findAll();
            }
            else
            {
                listaAuxObra = objAuxObraBEL.findAuxObraDate(beginDate, endDate);
            }

            sord = (sord == null) ? "" : sord;
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;

            if (_search)
            {
                switch (searchField)
                {
                    case "by_numeroAux":
                        listaAuxObra = listaAuxObra.Where(t => t.NumeroAux.Contains(searchString)).ToList();
                        break;
                    case "by_contratista":
                        listaAuxObra = listaAuxObra.Where(t => t.Contratista.ToUpper().Contains(searchString.ToUpper())).ToList();
                        break;
                    case "by_objetoCto":
                        listaAuxObra = listaAuxObra.Where(t => t.ObjetoCto.Contains(searchString.ToUpper())).ToList();
                        break;
                    case "by_anioCto":
                        listaAuxObra = listaAuxObra.Where(t => t.AnioCto.Contains(searchString)).ToList();
                        break;
                }
            }

            int totalRecords = listaAuxObra.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);

            if (sord.ToUpper() == "DESC")
            {
                //listaAuxObra = listaAuxObra.OrderByDescending(x => x.NumeroAux).ToList();
                listaAuxObra = listaAuxObra.OrderByDescending(x => x.AnioCto).ToList();
                listaAuxObra = listaAuxObra.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            else
            {
                //listaAuxObra = listaAuxObra.OrderBy(x => x.NumeroAux).ToList();
                listaAuxObra = listaAuxObra.OrderBy(x => x.AnioCto).ToList();
                listaAuxObra = listaAuxObra.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }

            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = listaAuxObra
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getAuxObraDet(string sidx, string sord, int page, int rows, bool _search,
                                        string searchField, string searchOper, string searchString, string auxObraID)
        {
            AuxiliarObraDet objAuxObraNroDet = new AuxiliarObraDet();
            objAuxObraNroDet.NumeroAux = auxObraID;
            List<AuxiliarObraDet> listaAuxObraDet;
            listaAuxObraDet = objAuxObraBEL.findAuxObraNroDet(objAuxObraNroDet);

            sord = (sord == null) ? "" : sord;
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;


            int totalRecords = listaAuxObraDet.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = listaAuxObraDet
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }


        // EXPORT TO EXCEL: INICIO
        [HttpGet]
        [ExportResultToExcel(exportedFileName: "AuxiliarObra.xlsx", tempDataKey: "AuxData")]
        public ActionResult ExportToExcelDate()
        {
            using (GridView grid = new GridView())
            {
                //grid.DataSource = from p in objAuxObraBEL.findAll()
                grid.DataSource = from p in objAuxObraBEL.findAuxObraDate(Utils.GlobalVarAux.fechaDesde, Utils.GlobalVarAux.fechaHasta)
                                  select new
                                  {
                                      Periodo = p.AnioCto,
                                      AuxNro = p.NumeroAux,
                                      Contratista = p.Contratista,
                                      CedRuc = p.CedRuc,
                                      Codigo = p.CodigoCto,
                                      Objeto = p.ObjetoCto,
                                      Fecha = p.FechaCto,
                                      Monto = p.MontoCto,
                                      Partida = p.Partida,
                                      Plazo = p.Plazo
                                  };
                grid.DataBind();
                TempData["AuxData"] = grid;
                
            }
            return View("findAuxObraDate");
        }
        // EXPORT TO EXCEL: FIN



        // ADD: AuxObra

        public ActionResult Create()
        {
            return View();
        }


        // DEL: AuxObra

        // UPD: AuxObra




    }
}

webAuxiliar/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Web.Mvc;
using model.DEL;
using model.BEL;

namespace webAuxiliar.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
    }
}

webAuxiliar/Views/AuxObra/findAuxObraDate.cshtml
@{
    ViewBag.Title = "Información Auxiliar Obras";
}
<br />

<!DOCTYPE html>
<html lang="es-ec">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    @*<meta name="viewport" content="width=device-width, initial-scale=1">*@
    @*<link rel="stylesheet" href="~/Content/font-awesome-4.7.0/css/font-awesome.css">*@

    @*<script type="text/ecmascript" src="~/Scripts/jquery-2.1.1.min.js"></script>
        <script type="text/ecmascript" src="~/Scripts/jqGridTrirand/jquery.jqGrid.js"></script>

        <script type="text/ecmascript" src="~/Scripts/jqGridTrirand/i18n/grid.locale-es.js"></script>
        <script src="~/Scripts/jquery-ui-1.12.1.js"></script>*@

    @*<link rel="stylesheet" type="text/css" media="screen" href="~/Content/themes/base/jquery-ui.css">
        <link rel="stylesheet" type="text/css" media="screen" href="~/Scripts/jqGridTrirand/css/ui.jqgrid.css">*@
</head>
<body>
    <fieldset>
        <div>
            <form>
                <table style="width:30%">
                    <tr>
                        <th>Fecha Desde</th>
                        <th>Fecha Hasta</th>
                        <th></th>
                    </tr>
                    <tr>
                        <td>@Html.TextBox("txtFechaDesde", string.Empty, new { @class = "datepicker", @type = "date" })</td>
                        <td>@Html.TextBox("txtFechaHasta", string.Empty, new { @class = "datepicker", @type = "date" })</td>
                        <td><input class="btn btn-primary" type="submit" value="Buscar" /></td>
                    </tr>
                </table>
            </form>
            <br />
            <table id="jqGridAux"></table>
            <div id="jqGridAuxPag"></div>
            <br />
            @*<button type="button" id="demo">Submit</button>*@
            @*<button id="exportar">Exportar a Excel</button>*@
            @*<input type="button" value="Imprimir Reporte" onclick="getSelectRows()" />*@
            @*@Html.ActionLink("REPORTES", "Index", "Report", new { id = "9532" }, new { target = "_blacnk" })*@
        </div>
    </fieldset>
    <div class="row" id="divReport">
    </div>
</body>
</html>

@using (Html.BeginForm("ExportToExcelDate", "AuxObra", FormMethod.Get))
{
}

@section scripts
{
    <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.min.css">
    <link rel="stylesheet" href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/free-jqGrid-4.15.2/ui.jqgrid.min.css">

    <script src="~/Scripts/jquery-3.2.1.min.js"></script>

    @*<<scripts para exportar>> INICIO *@
    <script src="~/Scripts/pdfmake0.1.33/pdfmake.min.js"></script>
    <script src="~/Scripts/pdfmake0.1.33/vfs_fonts.js"></script>
    <script type="text/javascript" language="javascript" src="~/Scripts/jszip3.1.4-22/jszip.min.js"></script>
    @*<<scripts para exportar>> FIN *@
    <script src="~/Scripts/free-jqGrid-4.15.2/i18n/grid.locale-es.js"></script>
    <script src="~/Scripts/free-jqGrid-4.15.2/jquery.jqgrid.min.js"></script>

    <script src="~/Scripts/jqGridExportToExcel.js"></script>
    <script src="~/Scripts/scriptAuxObra.js"></script>

    

}